spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG

# 1. Update the URL
spring.datasource.url=jdbc:postgresql://ep-lucky-fog-a4cbt9pm.us-east-1.aws.neon.tech/neondb?sslmode=require

# 2. Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3gWtUu6pGfTY

# 3. Update the Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Update the JPA/Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update